### ISSUE TITLE
Please add new version to scoop

### ISSUE THREAD

**Issue by DeadFlamingo** [Tichau/FileConverter#421]

**Comment by Tichau** [comment]
Note: FileConverter is already available on Winget and Chocolatey.

**Comment by drchiodo** [comment]
Thanks, 
`winget install AdrienAllard.FileConverter`
i was looking for Tichau.FileConverter

**Comment by jo-chemla** [comment]
It would be great to auto push new FileConverter releases to winget-pkgs to avoid relying on community doing the PR upstream. 

The standard way to do it is to use [winget-releaser](https://github.com/vedantmgoyal9/winget-releaser) (which uses Komac under the hood). It requires a Classic Github Personal Access Token with public_repo scope is created, following [this link](https://github.com/settings/tokens/new), then the Token can be added to the repo as a secret named `WINGET_ACC_TOKEN`. See below, that user also will have to fork the winget-pkgs repository.

> Notes:
> You will need to create a classic `Personal Access Token (PAT)` with `public_repo` scope. New fine-grained PATs aren't supported by the action.
> Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under the same account/organization as the project's repository. If you are forking winget-pkgs on a different account (e.g. bot/personal account), you can use the fork-user input to specify the username of the account where the fork is present.


```yml
name: Publish release to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@latest
        with:
          identifier: AdrienAllard.FileConverter
          installers-regex: 'x64\-setup\.msi'
          token: ${{ secrets.WINGET_ACC_TOKEN }}

```
